"""Taxonomy-driven classification coverage: queries generated by walking
data/taxonomy.json directly (real cities/property types/room counts, real
brands/models/years/prices, real sectors/subcategories/conditions) rather
than hand-picked examples — combinatorial coverage across the taxonomy's own
vocabulary, at a scale that catches a systemic classification gap rather
than needing a human to stumble onto one live example of it.
"""

import pytest

from repositories.taxonomy_repository import taxonomy_repository
from schema.taxonomy_models import Vertical
from services.classifier_service import _scan_term_occurrences, _vertical_scores, classify_query
from services.normalizer_service import normalize_query
from services.sanitizer_service import sanitize_query


def _classify(raw_query: str):
    return classify_query(normalize_query(sanitize_query(raw_query)))


def _generate_real_estate_cases() -> list[str]:
    property_types = taxonomy_repository.real_estate.get("סוגי_נכס", [])
    transaction_types = taxonomy_repository.real_estate.get("מצבי_עסקה", [])
    cities = taxonomy_repository.real_estate.get("מאפיינים_כלליים", {}).get("עיר", {}).get("דוגמאות", [])
    room_counts = [1, 2, 3, 4, 5, 6]

    cases = []
    for index, property_type in enumerate(property_types):
        city = cities[index % len(cities)] if cities else ""
        rooms = room_counts[index % len(room_counts)]
        cases.append(f"{property_type} {city} {rooms} חדרים")
    for index, transaction_type in enumerate(transaction_types):
        property_type = property_types[index % len(property_types)]
        city = cities[index % len(cities)] if cities else ""
        cases.append(f"{property_type} {transaction_type} {city}")
    return cases


def _generate_vehicle_cases() -> list[str]:
    prices = [40000, 60000, 90000, 150000]
    cases = []
    for index, (brand, brand_data) in enumerate(taxonomy_repository.vehicles.get("יצרנים", {}).items()):
        models = [model for model in brand_data.get("דגמים", []) if not model.isdigit()]
        if not models:
            continue
        model = models[index % len(models)]
        year_range = brand_data.get("שנות_ייצור", [2015, 2025])
        year = year_range[-1] if year_range else 2020
        price = prices[index % len(prices)]
        cases.append(f"{brand} {model} {year} עד {price} שח")
    for vehicle_type in taxonomy_repository.vehicles.get("סוגי_רכב", []):
        # "רכב" (the vertical's own name), not the bare vehicle_type alone:
        # a handful of vehicle types ("מסחרי", "פרטי") are *also* literal
        # values elsewhere in the taxonomy (מצבי_עסקה/בעלות for real
        # estate) -- genuinely, taxonomy-attested cross-vertical ambiguity,
        # not something a combinatorial generator should paper over by
        # testing the ambiguous word in isolation. See
        # test_vehicle_type_words_shared_with_other_verticals_are_a_real_tie
        # in test_classifier_service.py for that finding, documented rather
        # than hidden.
        cases.append(f"רכב {vehicle_type} עד 100000 שח")
    return cases


def _generate_used_goods_cases() -> list[str]:
    default_conditions = taxonomy_repository.used_goods.get("מאפיינים_כלליים", {}).get("מצב", ["משומש"])
    cases = []
    for sector, sector_data in taxonomy_repository.used_goods.get("סקטורים", {}).items():
        for index, (subcategory, subcategory_data) in enumerate(sector_data.get("תתי_קטגוריות", {}).items()):
            conditions = subcategory_data.get("מצב", default_conditions)
            condition = conditions[index % len(conditions)]
            cases.append(f"{subcategory} {condition}")
        # A real taxonomy condition value, not "למכירה": that word isn't
        # taxonomy vocabulary at all, and normalizer_service's fuzzy typo
        # correction (score_cutoff=85) happens to map it to real estate's
        # own "מכירה" term (a pre-existing normalizer quirk, not introduced
        # by this pass) -- see
        # test_lamechira_fuzzy_corrects_toward_real_estate in
        # test_normalizer_service.py for that finding, documented rather
        # than baked into this generator as if it were a clean, unambiguous
        # used-goods case.
        cases.append(f"{sector} {default_conditions[0]}")
    return cases


REAL_ESTATE_CASES = _generate_real_estate_cases()
VEHICLE_CASES = _generate_vehicle_cases()
USED_GOODS_CASES = _generate_used_goods_cases()


def test_generator_produces_dozens_of_cases_per_vertical():
    # A guard against the generator itself silently degenerating (e.g. an
    # empty taxonomy section) and every parametrized test below quietly
    # collecting zero cases.
    assert len(REAL_ESTATE_CASES) >= 15
    assert len(VEHICLE_CASES) >= 15
    assert len(USED_GOODS_CASES) >= 15


@pytest.mark.parametrize("query", REAL_ESTATE_CASES)
def test_real_estate_combinatorial_classification(query):
    result = _classify(query)
    assert result.vertical == Vertical.REAL_ESTATE, f"{query!r} -> {result.vertical}"


@pytest.mark.parametrize("query", VEHICLE_CASES)
def test_vehicle_combinatorial_classification(query):
    result = _classify(query)
    assert result.vertical == Vertical.VEHICLES, f"{query!r} -> {result.vertical}"


@pytest.mark.parametrize("query", USED_GOODS_CASES)
def test_used_goods_combinatorial_classification(query):
    result = _classify(query)
    assert result.vertical == Vertical.USED_GOODS, f"{query!r} -> {result.vertical}"


# Every (term, vertical) pair walked directly from the taxonomy (not
# hand-picked) where *every* match under that vertical is
# general_attributes-sourced -- "מלא"/"חשמלי"/"גז" were the reported cases,
# but the fix (TaxonomyTermMatch.is_general_attribute) is a blanket rule,
# and this proves it holds for every such pair, not just the two caught
# live. Deliberately excludes pairs like "פרטי"/רכב (also a real סוגי_רכב
# value -- private-car body type is genuine identifying signal, not just
# the generic "פרטי" ownership descriptor) and used-goods' own מצב values
# ("חדש", "משומש", ...), which double as real per-subcategory condition
# terms in addition to the general default -- those legitimately still
# score, and asserting otherwise would be testing a rule broader than the
# one actually implemented.
_PURELY_GENERAL_PAIRS = sorted(
    {
        (term, match.vertical)
        for term, matches in taxonomy_repository.term_index.items()
        for match in matches
        if match.is_general_attribute
        and all(m.is_general_attribute for m in matches if m.vertical == match.vertical)
    },
    key=lambda pair: (pair[0], pair[1].value),
)


def test_purely_general_attribute_pairs_exist_to_audit():
    assert len(_PURELY_GENERAL_PAIRS) >= 20


@pytest.mark.parametrize("term_and_vertical", _PURELY_GENERAL_PAIRS)
def test_purely_general_attribute_value_does_not_score_its_vertical_alone(term_and_vertical):
    term, vertical = term_and_vertical
    canonical = normalize_query(sanitize_query(term))
    occurrences = _scan_term_occurrences(canonical)
    scores = _vertical_scores(occurrences, canonical.split())
    assert scores[vertical] == 0, f"{term!r} alone scored {scores[vertical]} for {vertical}"
